services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "2626:8025"
      - "2525:1025"
    command:
      - --smtp-auth-accept-any
      - --smtp-auth-allow-insecure